[Feature] Add support for token authentication
streamnative/logstash-output-pulsar pull request #21
Opened 2022-10-20 11:01 UTC by JavaXiaoJun

2022-10-20 11:01 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/streamnative/logstash-output-pulsar?pullRequest=21) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/streamnative/logstash-output-pulsar?pullRequest=21) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/streamnative/logstash-output-pulsar?pullRequest=21) it.</sub>

2022-10-20 11:25 UTC, Shoothzj commented on README.md
> +    serviceUrl => "pulsar://10.2.0.7:6650"
```suggestion
    serviceUrl => "pulsar:/localhost:6650"
```

2022-10-20 11:37 UTC, Shoothzj requested changes

2022-10-20 11:37 UTC, Shoothzj commented on src/test/java/org/apache/pulsar/logstash/outputs/PulsarOutputExampleTest.java
> +    // 初始化配置信息
please use english here

2022-10-20 11:37 UTC, Shoothzj commented on src/test/java/org/apache/pulsar/logstash/outputs/PulsarOutputExampleTest.java
> +
shall we remove the useless blank line?

2022-10-20 11:37 UTC, Shoothzj commented on src/test/java/org/apache/pulsar/logstash/outputs/PulsarOutputExampleTest.java
> +    // topic
I think we can remove this annotation, it doesn't provide any extra information

2022-10-20 11:37 UTC, Shoothzj commented on src/test/java/org/apache/pulsar/logstash/outputs/PulsarOutputExampleTest.java
> +    // broker
I think we can remove this annotation, it doesn't provide any extra information

2022-10-20 11:37 UTC, Shoothzj commented on src/test/java/org/apache/pulsar/logstash/outputs/PulsarOutputExampleTest.java
> +        output.output(events);
we can assert the events size. A test case needs assert causes.

2022-10-20 11:37 UTC, Shoothzj commented on src/main/java/org/apache/pulsar/logstash/outputs/Pulsar.java
> +                client = buildTokenPulsar(configuration);
can token and tls be both enabled?

2022-10-20 15:05 UTC, JavaXiaoJun commented
@Shoothzj please review again

2022-10-23 12:15 UTC, Shoothzj commented on src/test/java/org/apache/pulsar/logstash/outputs/PulsarOutputExampleTest.java
> +            Assert.assertTrue("event0 contains the specified str", events.get(index).getField("message").toString().contains("message : hello test " + index));
Will this 0 not be incremented with it?

2022-10-23 12:17 UTC, Shoothzj commented
Currently, it seems the test-cases not set up the pulsar broker. It is not appropriate to submit test cases at this stage.
@JavaXiaoJun What do you think? How others have run this test?

2022-10-23 12:35 UTC, Shoothzj approved these changes

2022-10-23 12:35 UTC, merged